### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by renet** [emdgroup-liquid/liquid#23]
This is an umbrella issue for several refactoring tasks.

**Tasks**
- [x] Add path param to SVGO script
- [ ] Automate documentation of css variables
- [ ] #142
- [ ] #143
- [x] Rename menu item "Liquid"
- [x] Remove CSS reset from e2e tests
- [x] Remove CSS reset from component preview
- [ ] Make component preview code live-editable
- [ ] #144
- [ ] #145
- [x] Add missing documentation for React Bindings
- [ ] Config object for eleventy example shortcode
- [ ] #146
- [ ] #147
- [ ] Reactivate e2e tests in CI
- [ ] #148
- [ ] #150
- [ ] #151
- [ ] Do not use min-width for ld-label children
