### ISSUE TITLE
feat: enhance table component

### ISSUE THREAD

**Issue by zemirco** [emdgroup-liquid/liquid#469]
### Prerequisites

- [X] I know [how to contribute a proper feature request](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#requesting-new-features).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing feature requests](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) that already request this feature, without success.

### Describe the feature request

It would be great to either enhance the table or to build another component on top of the table to have something like a data grid.

### Describe the use case

We have very scientific and data heavy applications. Many of our applications deal with data where it is necessary to visualize it using rows and columns in a table.

Our customers are used to working with Excel, Jupyter Notebook, Google Docs, RStudio, etc. and expect similar functionality in our applications. 

### Describe preferred solution

I'd like to see the following features

- column resize
- column reorder via drag&drop
- row reorder via drag&drop
- grouping
- filters for multiple columns
- inline editing
- pivot features
- row / column freeze
- hiding / showing columns
- row expansion
- adding / deleting rows
- empty state when table empty
- empty state when search returns zero items

### Describe alternatives

**Edison™ Design System**
https://edisondesignsystem.com/datagrid?tab=0
![image](https://user-images.githubusercontent.com/1132354/212284503-c13650fa-a463-407c-9490-e3093c3c78ed.png)

**react-data-grid**
https://adazzle.github.io/react-data-grid/#/common-features
![image](https://user-images.githubusercontent.com/1132354/212283179-0bf68ba1-7f4f-49c2-9da0-85f37247b8d6.png)

**MUI Data grid**
https://mui.com/x/react-data-grid/
![image](https://user-images.githubusercontent.com/1132354/212283436-61f61fae-e37b-4224-9942-9afdb6adeff0.png)

**React Data Grid**
https://reactdatagrid.io/demo
![image](https://user-images.githubusercontent.com/1132354/212283533-eae63be9-d437-48b2-b96b-e21936318582.png)

**AG Grid**
https://www.ag-grid.com/react-data-grid/sparklines-overview/
![image](https://user-images.githubusercontent.com/1132354/212283743-b35f5f1a-0bb3-4d0d-bce2-8ac6e775ca67.png)

**KendoReact Data Grid**
https://www.telerik.com/kendo-react-ui/components/grid/
![image](https://user-images.githubusercontent.com/1132354/212283910-c2b64741-8817-4575-88ea-4d3d60fa45cd.png)

**Ignite UI**
https://www.infragistics.com/products/ignite-ui-react/react/components/grids/data-grid
![image](https://user-images.githubusercontent.com/1132354/212284036-429ed64d-8c49-4fbf-9c83-ef38e876f859.png)

**Syncfusion**
https://ej2.syncfusion.com/react/demos/?_gl=1*nt9t34*_ga*MTYyNjIyNDcwMC4xNjczNTk5Nzkw*_ga_WC4JKKPHH0*MTY3MzU5OTc5MC4xLjAuMTY3MzU5OTc5MC4wLjAuMA..&_ga=2.12839479.1625363014.1673599790-1626224700.1673599790#/material/grid/overview
![image](https://user-images.githubusercontent.com/1132354/212284323-1b0dc8d7-7eda-4d77-afa9-55bef93f4ab1.png)

**Ant Design**
https://ant.design/components/table
![image](https://user-images.githubusercontent.com/1132354/212284661-11f33853-a553-4281-abb9-44df54374c68.png)

**Palantir Blueprint**
https://blueprintjs.com/docs/#table/features
![image](https://user-images.githubusercontent.com/1132354/212289230-6b672c18-a895-4eed-ad41-d45009186167.png)

### Additional information

✨🎉🎁🥽🥼🏆

**Comment by borisdiakur** [comment]
Hi @zemirco 👋
Thanks a lot for this issue, that's a big one! I've labeled it as an _umbrella issue_: 

> An umbrella issue contains multiple issues and needs to be split into separate issues eventually.

_Umbrella issues_ are usually easy to spot by their vague name: In this concrete case we have "enhance table component" 😉

It would be great if you split it up into several concrete feature requests, because otherwise it is difficult to vote, or rather evaluate the votes on the features that are really required. Smaller, more concrete issues help up prioritize and keep our release cycles short.

Thanks again, your input is much appreciated 🙏

**Comment by zemirco** [comment]
Ok, no problem. Don't be shocked I will open a couple of issues this week 🚀

**Comment by borisdiakur** [comment]
Closing umbrella issue in favor of #470, #472 and #473. 🙏
